feat: add api to manage Ingredients
OmriBarZik/foody-anyway pull request #16
Opened 2022-12-28 17:50 UTC by OmriBarZik

Added new endpoints to the site

* add single Ingredient
* update single Ingredient
* remove single Ingredient
* get single Ingredient
* get multiple Ingredient

Added Zod for schema validations

2022-12-28 18:29 UTC, InbarDanieli requested changes

2022-12-28 18:29 UTC, InbarDanieli commented on lib/ingredient.ts
> +  const updatedIngredient = await collection.findOneAndUpdate(
what will happen if this id doesn't exist?

2022-12-28 18:29 UTC, InbarDanieli commented on lib/ingredient.ts
> +export async function getIngredients(): Promise<Ingredient[]> {
did you add type to all the promises?

2022-12-29 08:14 UTC, OmriBarZik commented on lib/ingredient.ts
> +  const updatedIngredient = await collection.findOneAndUpdate(
It will return an null of no object is found

2022-12-29 08:14 UTC, OmriBarZik commented on lib/ingredient.ts
> +export async function getIngredients(): Promise<Ingredient[]> {
Done

2022-12-29 08:19 UTC, InbarDanieli approved these changes

2022-12-29 08:19 UTC, merged