feat: add sign-in page
OmriBarZik/foody-anyway pull request #20
Opened 2023-01-10 13:46 UTC by InbarDanieli

2023-01-10 19:17 UTC, OmriBarZik requested changes

2023-01-10 19:17 UTC, OmriBarZik commented on pages/api/auth/[...nextauth].ts
> +console.log(process.env.NEXTAUTH_URL);
@InbarDanieli please remove log

2023-01-10 19:17 UTC, OmriBarZik commented on pages/login/index.tsx
> +  session && session.user && router.replace("/");
@InbarDanieli  please make it an if statement like so

```ts
if (session && session.user) router.replace("/");
```

2023-01-11 08:29 UTC, InbarDanieli commented on pages/api/auth/[...nextauth].ts
> +console.log(process.env.NEXTAUTH_URL);
done

2023-01-11 08:29 UTC, InbarDanieli commented on pages/login/index.tsx
> +  session && session.user && router.replace("/");
done

2023-01-12 15:08 UTC, OmriBarZik approved these changes

2023-01-12 15:08 UTC, merged